name: Daily Smoke Test

on:
  push:
    branches: [ main ]
  schedule:

#    minute (0 - 59)
#    hour (0 - 23)
#    day of the month (1 - 31)
#    month (1 - 12 or JAN-DEC)
#    day of the week (0 - 6 or SUN-SAT)

  # Runs every 5:30 AM on Tuesdays and Thursdays
    - cron: '30 5 * * 2,4'
    

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:

      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: mvn clean test -DsuiteXmlFile=src/test/java/testng.xml

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: index-${{ github.run_number }}.html
          path: ./reports/SparkReport
          if-no-files-found: ignore
          retention-days: 2
          compression-level: 6
          overwrite: true

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0
        with:
          token: ${{ github.token }}

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: github-pages
          path: ./reports/SparkReport
          retention-days: 7

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ github.token }}
