name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven

    - name: Run tests with Maven
      run: mvn clean test -DsuiteXmlFile=src/test/java/testng.xml

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: Spark.html
        path: ./reports/SparkReport/index.html
        if-no-files-found: ignore
        retention-days: 2
        compression-level: 6
        overwrite: true

    - name: GitHub Pages v3
      # You may pin to the exact commit or the version.
      # uses: peaceiris/actions-github-pages@b80a30e9bf3c1ec596532c3813f0aff094f555e2
      uses: peaceiris/actions-github-pages@v3.1.12
      with:
        # 
        # deploy_key: # optional
        # # 
        # github_token: # optional
        # # 
        # personal_token: # optional
        # # 
        # publish_branch: # optional, default is gh-pages
        # # 
        publish_dir: ./reports
        # # 
        # external_repository: # optional
        # # If empty commits should be made to the publication branch
        # allow_empty_commit: # optional, default is false
        # # If existing files in the publish branch should be not removed before deploying
        # keep_files: # optional, default is false
        # # Keep only the latest commit on a GitHub Pages branch
        # force_orphan: # optional, default is false
        # # Set Git user.name
        # user_name: # optional
        # # Set Git user.email
        # user_email: # optional
        # # Set custom commit message
        # commit_message: # optional
        # # Set tag name
        # tag_name: # optional
        # # Set tag message
        # tag_message: # optional
